image: maven:latest

stages:
  - build 
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    - frontend/greenide/node_modules/

build:
  tags:
    - SWTP
  stage: build
  script:
    - echo "building"
    - "mvn install"
    - cd src/main/java
    - javac hello/*.java
    - java hello.HelloWorld

test:
  stage: test
  script:
    - mvn clean test -Dtest=hello.GreeterTest

test_frontend:
  stage: test
  image: node:12-slim
  variables:
    DISPLAY: ':99.0'
  script:
    - cd frontend/greenide
    - apt-get update
    - apt-get install -y xvfb libxtst6 libnss3 libgtk-3-0 libxss1 libasound2 libsecret-1-0 git
    - npm ci
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm run test

package_extension:
  stage: deploy
  image: node:latest
  script:
    - cd frontend/greenide
    - npm install
    - npm install -g vsce
    - npm run package
  artifacts:
    paths:
      - frontend/greenide/greenide.vsix

deploy:
  stage: deploy
  image: ruby:latest
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=server-backend-swtp-13 --api-key=$HEROKU_API_TOKEN --skip-cleanup 
rules:
    - if: '$CI_COMMIT_REF_NAME== "feature/backend-server"'
      changes:
      - backend/server/*
      when: always
