image: maven:latest

stages:
  - build
  - test 
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  tags:
    - SWTP
  stage: build
  script:
    - echo "building"
    - "mvn install"
    - cd src/main/java/hello
    - java -cp hello.HelloWorld

test:
  stage: test
  script:
    - java GreeterTest.java
 

deploy:
  stage: deploy
  script:
    - echo "deploying"  
  only:
    - main
